apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: replit-workspaces
  namespace: replit-clone
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard
