apiVersion: v1
kind: ServiceAccount
metadata:
  name: replit-api-sa
  namespace: replit-clone
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: sandbox-manager
  namespace: replit-clone
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/status", "services"]
    verbs: ["get", "list", "watch", "create", "delete", "patch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: replit-api-sandbox-manager
  namespace: replit-clone
subjects:
  - kind: ServiceAccount
    name: replit-api-sa
    namespace: replit-clone
roleRef:
  kind: Role
  name: sandbox-manager
  apiGroup: rbac.authorization.k8s.io
