apiVersion: v1
kind: Secret
metadata:
  name: replit-secrets
  namespace: replit-clone
type: Opaque
stringData:
  postgres-url: "postgresql://postgres:postgres@postgres-svc:5432/mini_replit"
  mongo-url: "mongodb://mongo-svc:27017/mini_replit"
  jwt-secret: "change-this-to-a-secure-secret"
